# Goal: To say Hello and tell the title / Name of repository

# Start with naming your workflow
name: Hello

# when the workflow runs
on:  
  # push:            # it shows workflows start when we push any changes on github
  #   paths-ignore:
  #     - 'README.md'
  workflow_dispatch:

# what the workflow does
jobs:
  # name of your Jobs
  greet:     #jobs 1
    # where the job runs (OS)
    runs-on: ubuntu-latest
    # the sequence of steps the job does
    steps:
      - name: Say hello
        run: echo "Hello friends"

      - name: welcome
        run: echo "Welcome friends"

  repo-name:    #jobs 2 
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Show Repository Name
        run: echo "The Repo Name is ${{ github.event.repository.name }}"  # inbuilt 