name: code lint
on:
   workflow_call:

jobs:
  code-linter-and-test:
    runs-on: ubuntu:latest 
    strategy:
      matrix:
        python-version: ['3.12','3.13','3.14']

    steps:
   
      - name: check out repo
        uses: actions/checkout@v7

   
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{matrix.python-version}}

   
      - name: install dependencies
        uses: pip install -r requirements.txt


       - name: code lint
         run: ruff check .

       - name: code tests
         run: pytest

