# Goal: To check if the python code is syntactically correct

name: Code Lint

on:
    workflow_call:

jobs:
    
    code-linter-and-test:
        strategy:
          matrix:
            python-versions: ['3.12','3.13','3.14']

        runs-on: ubuntu-latest   # github hosted, this is dedicated server used to run the specific job
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                #python-version: 3.14
                python-version: ${{matrix.python-versions}}

            - name: Install Dependencies
              run: pip install -r requirements.txt
              
            - name: Code Lint
              run: ruff check . --fix

            - name: Code Tests
              run: pytest