name: code lint

on:
   push:

jobs:
  code-linter-and-test:
    runs-on: ubuntu:latest 
    strategy:
      matrix:
        python-version: ['3.12','3.13','3.14']

    steps:
    # fetch the repository
      - name: check out repo
        uses: actions/checkout@v7

    # setup the python 
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{matrix.python-version}}

    # install dependency 
      - name: install dependencies
        uses: pip install -r requirements.txt


       - name: code lint
         run: ruff check .

       - name: code tests
         run: pytest

