# Goal : To scan the code for tokens, secrets, API Keys, or any leaked Passwords so that
# if found, we can quickly rotate(remove the existing code and add the new code) the exposed tokens/keys/etc

# name of the workflow
name: Secrets Scan

# Reusable Workflow which can be called again and again wherever needed
on: 
    workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0 # from the very first commit pull all the code, that tells Git to fetch the entire commit history, along with all branches and tags, instead of performing a shallow clone. and if fetch-depth: 0 not used it will take the code from current commit

            - name: Scan for Leaks
              #uses: dortort/betterleaks-action@v0.1.0
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this is inbuilt token in github when we mentioned GITHUB_TOKEN it will take GITHUB token from repository 
              #with:
                #config: .github/.gitleaks.toml 
              #continue-on-error: true 
            